aquitance/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('contact/', views.AboutTechView.as_view(), name='contact'),
]

aquitance/aquitance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls', namespace='products')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

aquitance/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('product_detail/', views.product_detail, name='product_detail'),
    path('category/', views.category, name='category'),
    path('category/<slug:slug>/', views.category_list, name='category_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('create/', views.product_create, name='product_create'),
    path('products/<int:product_id>/edit/', views.product_edit, name='product_edit'),
    path('basket/<str:username>/', views.basket, name='basket'),
]

aquitance/products/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
NUM_OF_WORDS = 20


class Category(models.Model):
    title = models.CharField(max_length=200,
                             verbose_name='Заглавие')
    image = models.ImageField(upload_to="photos_category/%Y/%m/%d/",
                              blank=True,
                              verbose_name='Изображение категории')
    slug = models.SlugField(unique=True,
                            verbose_name='Уникальный URL')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.title}'


class Product(models.Model):
    image = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True, verbose_name='Изображение')
    title = models.CharField(max_length=30, verbose_name='Наименование товара')
    description = models.TextField(max_length=400, verbose_name='Описание', blank=True)
    price = models.IntegerField(verbose_name='Цена')
    category = models.ForeignKey(
        Category,
        related_name='products_category_related',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Категория',
        help_text='Выберите группу'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='products_author_related',
        verbose_name='Автор'
    )
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.title[:NUM_OF_WORDS]

    class Meta:
        ordering = ("-pub_date",)

aquitance/products/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('image', 'title', 'description', 'price', 'category')

aquitance/products/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import ProductForm

from .models import *

num_of_pub: int = 9


def general_paginator(request, paginator):
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'products/index.html'
    products_list = Product.objects.all()
    paginator = Paginator(products_list, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def category(request):
    template = 'products/category.html'
    all_category = Category.objects.all()
    paginator = Paginator(all_category, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def category_list(request, slug):
    category_name = get_object_or_404(Category, slug=slug)
    products = category_name.products_category_related.order_by('-pub_date')
    paginator = Paginator(products, num_of_pub)
    page_obj = general_paginator(request, paginator)
    template = 'products/category_list.html'
    context = {
        'page_obj': page_obj,
        'category_name': category_name,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    products_list = author.products_author_related.order_by('-pub_date')
    paginator = Paginator(products_list, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'products/profile.html', context)


def basket(request, username):
    author = get_object_or_404(User, username=username)
    products_list = author.products_author_related.order_by('-pub_date')
    paginator = Paginator(products_list, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'products/basket.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {
        'product': product,
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def product_create(request):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        create_product = form.save(commit=False)
        create_product.author = request.user
        create_product.save()
        return redirect('products:profile', create_product.author)
    context = {
        'form': form,
    }
    return render(request, 'products/create_product.html', context)


def product_edit(request, product_id):
    edit_product = get_object_or_404(Product, pk=product_id)
    if request.user != edit_product.author:
        return redirect('products:product_detail', product_id)
    form = ProductForm(request.POST or None, instance=edit_product)
    if form.is_valid():
        form.save()
        return redirect('products:product_detail', product_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'products/create_product.html', context)

aquitance/templates/products/basket.html
{% extends 'base.html' %}
{% block title %}Корзина{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Title</h5>
        <p class="card-text">description</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">price</li>
        <li class="list-group-item">Автор: </li>
        <li class="list-group-item">Всего товаров автора:</li>
      </ul>
      <div class="card-body">
        <a href="" class="card-link">
          Подробнее
        </a>
        <a
          class="card-link"
          href=""
          >
          Категория:
        </a>
      </div>
      <div class="card-footer">
        <small class="text-muted">Дата публикации: </small>
      </div>
    </div>
  </div>
</div>
{% endblock %}

aquitance/templates/products/category.html
{% extends 'base.html' %}
{% block title %}
  Страница категорий
{% endblock title %}
{% block content %}
  <h1 >Полный список категорий</h1>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  {% for category in page_obj %}
    {% include 'includes/category_includes.html' %}
  {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock content %}

aquitance/templates/products/category_list.html
{% extends 'base.html' %}
{% block title %}
  {{ category_name.title }}
{% endblock title %}
{% block content %}
<h1>{{ category_name.title}}</h1>
<p>{{ category_name.description }}</p>
<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for product in page_obj %}
    <div class="col">
      <div class="card h-100">
        <a href="{% url 'products:product_detail' product.pk %}">
          <div class="card-img-top text-center">
            {% if product.image %}
              {{ product.image }}
            {% else %}
              Нет изображения
            {% endif %}
          </div>
        </a>
        <div class="card-body">
          <h5 class="card-title">{{ product.title|linebreaksbr }}</h5>
          <p class="card-text">{{ product.description|linebreaksbr }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{ product.price }} ₽</li>
          <li class="list-group-item">Продавец: {{ product.author.get_full_name }}</li>
          <li class="list-group-item">Всего товаров автора: {{ product.author.products_author_related.count }}</li>
        </ul>
        <div class="card-body">
          <a href="{% url 'products:product_detail' product.pk %}" class="card-link">
            Подробнее
          </a>
          {% if product.category %}
            <a
              class="card-link"
              href="{% url 'products:category_list' product.category.slug %}"
            >
              Категория: {{ product.category }}
            </a>
            {% endif %}
        </div>
        <div class="card-footer">
          <small class="text-muted">Дата публикации: {{ product.pub_date|date:"d E Y" }}</small>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% include 'includes/paginator.html' %}
{% endblock %}

aquitance/templates/products/create_product.html
{% extends 'base.html' %}
{% block title %}
  Новый товар
{% endblock title %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактировать запись
              {% else %}
                Добавить запись
              {% endif %}
            </div>
            <div class="card-body">
              {% load user_filters %}
              {% if form.errors %}
                {% for field in form %}
                  {% for errors in field.errors %}
                    <div class="alert alert-danger">
                      {{ errors|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ errors|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger" >*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
                {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

aquitance/templates/products/index.html
{% extends 'base.html' %}
{% block title %}
  Главная страница
{% endblock title %}
{% block content %}
  <h1 >Последние обновления на сайте</h1>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  {% for product in page_obj %}
    {% include 'includes/product.html' %}
  {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock content %}

aquitance/templates/products/product_detail.html
{% extends 'base.html' %}
{% block title %}
  Товар {{ product_obj.fullstory|truncatechars:30 }}
{% endblock title %}
{% block content %}
  <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <p>{{ product.title|linebreaksbr }}</p>
          <p>{{ product.image }}</p>
          <p>{{ product.price }} ₽</p>
          <p>{{ product.description|linebreaksbr }}</p>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ product.pub_date|date:"d E Y" }}
            </li>
            <li class="list-group-item">
              Автор: {{ product.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ product.author.products_author_related.count }}
            </li>
            {% if product.category %}
              <li class="list-group-item">
              Категория: {{ product.category }}
              <a
                href="{% url 'products:category_list' product.category.slug %}"
                class="btn btn-primary"
                color="red">
                Все товары категории
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              <a
                class="btn btn-primary"
                href="{% url 'products:profile' product.author %}"
                role="button">
                Все товары пользователя
              </a>
            </li>
            {% if user == product.author %}
              <li class="list-group-item">
              <a
                class="btn btn-primary"
                href="{% url 'products:product_edit' product.pk %}"
                role="button">
                Редактировать
              </a>
            </li>
            {% endif %}
          </ul>
        </aside>
      </div>
    </main>
{% endblock %}

aquitance/templates/products/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
{% block content %}
  <main>
      <div class="container py-5">
        <h1>Все товары пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: <span>{{ author.products.count }}</span></h3>
        <a
          class="btn btn-primary"
          href="#"
          role="button">
          Все товары пользователя
        </a>
        <br>
        <br>
        {% for product in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ product.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ product.pub_date|date:"d E Y" }}
              </li>
              <li>
                {{ product.category }}
              </li>
            </ul>
            <a class="link-primary" href="{% url 'products:product_detail' product.pk %}">Подробнее</a>
            <br>
            <br>
            {% if product.group %}
              <button type="button" class="btn btn-outline-info">
                <a
                href="{% url 'products:category_list' product.category.slug %}"
                color="red">
                Все записи группы
                </a>
              </button>
            {% endif %}
            </article>
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div>
    </main>
{% endblock content %}