aquitance/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('contact/', views.AboutTechView.as_view(), name='contact'),
]

aquitance/aquitance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls', namespace='products')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

aquitance/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('product_detail/', views.product_detail, name='product_detail'),
    path('category/', views.category, name='category'),
    path('category/<slug:slug>/', views.category_list, name='category_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('create/', views.product_create, name='product_create'),
    path('products/<int:product_id>/edit/', views.product_edit, name='product_edit'),
    path('basket/<str:username>/', views.basket, name='basket'),
]

aquitance/products/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
NUM_OF_WORDS = 20


class Category(models.Model):
    title = models.CharField(max_length=200,
                             verbose_name='Заглавие')
    image = models.ImageField(upload_to="photos_category/%Y/%m/%d/",
                              blank=True,
                              verbose_name='Изображение категории')
    slug = models.SlugField(unique=True,
                            verbose_name='Уникальный URL')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.title}'


class Product(models.Model):
    image = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True, verbose_name='Изображение')
    title = models.CharField(max_length=30, verbose_name='Наименование товара')
    description = models.TextField(max_length=400, verbose_name='Описание', blank=True)
    price = models.IntegerField(verbose_name='Цена')
    category = models.ForeignKey(
        Category,
        related_name='products_category_related',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Категория',
        help_text='Выберите группу'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='products_author_related',
        verbose_name='Автор'
    )
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.title[:NUM_OF_WORDS]

    class Meta:
        ordering = ("-pub_date",)

aquitance/products/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('image', 'title', 'description', 'price', 'category')

aquitance/products/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import ProductForm

from .models import *

num_of_pub: int = 9


def general_paginator(request, paginator):
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'products/index.html'
    products_list = Product.objects.all()
    paginator = Paginator(products_list, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def category(request):
    template = 'products/category.html'
    all_category = Category.objects.all()
    paginator = Paginator(all_category, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def category_list(request, slug):
    category_name = get_object_or_404(Category, slug=slug)
    products = category_name.products_category_related.order_by('-pub_date')
    paginator = Paginator(products, num_of_pub)
    page_obj = general_paginator(request, paginator)
    template = 'products/category_list.html'
    context = {
        'page_obj': page_obj,
        'category_name': category_name,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    products_list = author.products_author_related.order_by('-pub_date')
    paginator = Paginator(products_list, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'products/profile.html', context)


def basket(request, username):
    author = get_object_or_404(User, username=username)
    products_list = author.products_author_related.order_by('-pub_date')
    paginator = Paginator(products_list, num_of_pub)
    page_obj = general_paginator(request, paginator)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'products/basket.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {
        'product': product,
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def product_create(request):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        create_product = form.save(commit=False)
        create_product.author = request.user
        create_product.save()
        return redirect('products:profile', create_product.author)
    context = {
        'form': form,
    }
    return render(request, 'products/create_product.html', context)


def product_edit(request, product_id):
    edit_product = get_object_or_404(Product, pk=product_id)
    if request.user != edit_product.author:
        return redirect('products:product_detail', product_id)
    form = ProductForm(request.POST or None, instance=edit_product)
    if form.is_valid():
        form.save()
        return redirect('products:product_detail', product_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'products/create_product.html', context)

aquitance/templates/includes/category_includes.html
<div class="col">
  <div class="card h-100">
    <a href="{% url 'products:category_list' category.slug %}">
      <div class="card-img-top text-center">
        {% if category.image %}
          {{ category.image }}
        {% else %}
          Нет изображения
        {% endif %}
      </div>
    </a>
    <div class="card-body">
      <h5 class="card-title">{{ category.title|linebreaksbr }}</h5>
      <p class="card-text">{{ category.description|linebreaksbr }}</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Всего товаров в категории: {{ category.products_category_related.count }}</li>
    </ul>
    <div class="card-body">
      <a href="{% url 'products:category_list' category.slug %}" class="card-link">
        Подробнее
      </a>
    </div>
  </div>
</div>

aquitance/templates/includes/footer.html
{% load static %}
<div class="footer-copyright text-center py-3">
  <p>© {{ year }} Copyright <span style="color:black">Aqui</span><span style="color:black">tance</span></p>
</div>

aquitance/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: rgb(255, 245, 238, 0.5)">
    <div class="container">
        <a class="navbar-brand" href="{% url 'products:index'  %}">
            <img src="{% static 'img/aquitance.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:black">A</span><span style="color:black">quitance</span>
        </a>
        <ul class="nav nav-pills">
            {% with request.resolver_match.view_name as view_name %}
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'products:index' %}active{% endif %}"
                   href="{% url 'products:index' %}"
                >
                    Главная
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
                   href="{% url 'about:author' %}"
                >
                    Об авторе
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'about:contact' %}active{% endif %}"
                   href="{% url 'about:contact' %}"
                >
                    Контакты
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'products:category' %}active{% endif %}"
                   href="{% url 'products:category' %}"
                >
                    Категории товаров
                </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'products:product_create' %}active{% endif %}"
                   href="{% url 'products:product_create' %}"
                >
                    Разместить объявление
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:password_change_form' %}active{% endif %}"
                   href="{% url 'users:password_change_form' %}"
                >
                    Изменить пароль
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
                   href="{% url 'users:logout' %}"
                >
                    Выйти
                </a>
            </li>
            <li>
                <a class="nav-link {% if view_name  == 'products:profile' %}active{% endif %}"
                   href="{% url 'products:profile' user %}"
                >
                    Пользователь: {{ user.username }}
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link {% if view_name  == 'products:basket' %}active{% endif %}"
                   href="{% url 'products:basket' user %}"
                >
                    Корзина
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
                   href="{% url 'users:login' %}"
                >
                    Войти
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
                   href="{% url 'users:signup' %}"
                >
                    Регистрация
                </a>
            </li>
            {% endif %}
            {% endwith %}
        </ul>
    </div>
</nav>

aquitance/templates/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Предыдущая
            </a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active">
            <span class="page-link">{{ i }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Следующая
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Последняя
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

aquitance/templates/includes/product.html
<div class="col">
    <div class="card h-100">
      <a href="{% url 'products:product_detail' product.pk %}">
        <div class="card-img-top text-center">
          {% if product.image %}
            {{ product.image }}
          {% else %}
            Нет изображения
          {% endif %}
        </div>
      </a>
      <div class="card-body">
        <h5 class="card-title">{{ product.title|linebreaksbr }}</h5>
        <p class="card-text">{{ product.description|linebreaksbr }}</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ product.price }} ₽</li>
        <li class="list-group-item">Продавец:
          <a
          class="card-link"
          href="{% url 'products:profile' product.author %}"
          >
            {{ product.author.get_full_name }}
          </a>
        </li>
        <li class="list-group-item">Всего товаров автора: {{ product.author.products_author_related.count }}</li>
      </ul>
      <div class="card-body text-center">
        <a href="{% url 'products:product_detail' product.pk %}" class="card-link">
          Подробнее
        </a>
        {% if product.category %}
        <a
          class="card-link"
          href="{% url 'products:category_list' product.category.slug %}"
          >
          {{ product.category }}
        </a>
        {% endif %}
      </div>
      <div class="card-footer text-center">
        <small class="text-muted">Дата публикации: {{ product.pub_date|date:"d E Y" }}</small>
      </div>
    </div>
</div>